[[deqp]]
deqp = "/deqp/modules/gles2/deqp-gles2"
caselists = ["/deqp/mustpass/gles2-master.txt"]
deqp_args = [
    "--deqp-surface-width=256",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-visibility=hidden"
]
version_check = "GL ES 2.0.*git"
renderer_check = "i915"

[[deqp]]
deqp = "/deqp/external/openglcts/modules/glcts"
caselists = ["/deqp/mustpass/gles2-khr-master.txt"]
deqp_args = [
    "--deqp-surface-width=256",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-visibility=hidden"
]

[[piglit]]
piglit_folder = "/piglit"
# We use "gpu" to skip running glslparser tests, with the assumption that
# they're covered by the llvmpipe run.
profile = "gpu"
process_isolation = true
