[[deqp]]
deqp = "/deqp/modules/gles2/deqp-gles2"
caselists = ["/deqp/mustpass/gles2-master.txt"]
skips = ["install/all-skips.txt", "install/nouveau-gm20b-skips.txt"]
deqp_args = [
    "--deqp-surface-width=256",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-visibility=hidden"
]
renderer_check = "NV12B"
version_check = "GL ES 3.2"

[[deqp]]
deqp = "/deqp/modules/gles3/deqp-gles3"
caselists = ["/deqp/mustpass/gles3-master.txt"]
skips = ["install/all-skips.txt", "install/nouveau-gm20b-skips.txt"]
deqp_args = [
    "--deqp-surface-width=256",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-visibility=hidden"
]

[[deqp]]
deqp = "/deqp/modules/gles31/deqp-gles31"
caselists = ["/deqp/mustpass/gles31-master.txt"]
skips = ["install/all-skips.txt", "install/nouveau-gm20b-skips.txt"]
deqp_args = [
    "--deqp-surface-width=256",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-visibility=hidden"
]

[[deqp]]
deqp = "/deqp/external/openglcts/modules/glcts"
caselists = [
	  "/deqp/mustpass/gles2-khr-master.txt",
	  "/deqp/mustpass/gles3-khr-master.txt",
	  "/deqp/mustpass/gles31-khr-master.txt"
]
skips = ["install/all-skips.txt", "install/nouveau-gm20b-skips.txt"]
deqp_args = [
    "--deqp-surface-width=256",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-visibility=hidden"
]
